### ISSUE TITLE
Discord4J fails to compile using Java 9.0.1

### ISSUE THREAD

**Issue by D3add3d** [Discord4J/Discord4J#363]
### Description
Discord4J fails to compile using Java 9.0.1 throwing a NoClassDefFoundError

### Steps to Reproduce
1. Add Discord4J as a JAR dependency
2. Use Java 9.0.1 in IntelliJ to compile the project using the example code from README.md

...

**Expected behavior:** The project should have compiled and ran

**Actual behavior:** The compilation threw "java.lang.NoClassDefFoundError: sun/net/spi/nameservice/dns/DNSNameService"

**Stacktrace (if applicable):** https://hastebin.com/irajibinuz.tex

**Version affected:** 2.9.1 shaded jar

**Comment by danthonywalker** [comment]
I think you mean it won't *run* (but compile is also true).
The *running* issue was fixed as of 5bb3f8a. Compiling is still a problem, but it's not our fault. If compiled under Java 8, it'll run under Java 9.

**Comment by D3add3d** [comment]
yes, sorry I meant run

**Comment by danthonywalker** [comment]
No worries, you weren't wrong about compiling either, but the distinguishing between title and the actual error needed to be made. If you use the latest dev commit, you'll be able to run under Java 9.

**Comment by MinnDevelopment** [comment]
What is preventing you from compiling using jdk 9?

**Comment by danthonywalker** [comment]
Koloboke
